### ISSUE TITLE
Expose listPath Methode of SMBConnection

### ISSUE THREAD

**Issue by ShadyM4ybe** [pschmitt/easypysmb#22]
Currently it is not possible to use the listPath() Method from the SMBConnection Package. I think this is a important feature of the PYSMB Library as it is used to check if a file already exists on the Destination Server. Please expose it in your Code to vastly improve usability

**Comment by pschmitt** [comment]
Doesn't the `ls` function cover your usecase?

I added it to the documentation in c44e2009528c6bc2d8933e9677b0a6e399bccf6b

**Comment by ShadyM4ybe** [comment]
The `ls` Function was not documented so I did not knew it existed. It does cover my usecase. Thank you very much for the quick reply!
