### ISSUE TITLE
Failed to store binary file to smb

### ISSUE THREAD

**Issue by VbanlangenV** [pschmitt/easypysmb#3]
When I try to store a binary file to smb server,  such as  image.bin,   the destination file is a damaged one when smb.store_file completed.

The issue was fixed after I changed the code as below:

    def store_file(self, file_obj, dest_path=None, share_name=None, retries=3):
        if not dest_path:
            dest_path = self.file_path
        assert dest_path, 'Destination path is unset'
        share_name, dest_path = self.__guess_share_name(dest_path, share_name)
        if type(file_obj) is str or type(file_obj) is str:
--            file_obj = open(file_obj)
++          file_obj = open(file_obj,'rb')

**Comment by pschmitt** [comment]
Thanks for the feedback. Would you mind opening a PR for this?
